name: ci

on:
  schedule:
    # build every first of the month
    - cron: '0 0 1 * *'
  push:
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push (push only in main branch)
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/pluswerk/solr-proxy:latest,ghcr.io/pluswerk/solr-proxy:${{ steps.date.outputs.date }}
